server:
  port: 8081

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: document-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/documents/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/docucast-realm